server:
  port: 8097

#启动服务名称
spring:
  application:
    name: lotteryb-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #序列化与反序列化禁止科学计数配置
    serialization:
      WRITE_BIGDECIMAL_AS_PLAIN: true
      #USE_BIG_DECIMAL_FOR_FLOATS: true
  # aws与本地环境切换（aws: prod  本地：dev)
  profiles:
    active: dev

#mybatispluse
mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml,classpath*:/commonmapping/*.xml
  type-aliases-package: com.didu.lotteryshop

