server:
  port: 8092
  #servlet:
   #context-path: /eurekabase
#  session:
#    cookie:
#      name: SESSIONID
spring:
  application:
    name: base-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #序列化与反序列化禁止科学计数配置
    serialization:
      WRITE_BIGDECIMAL_AS_PLAIN: true
      #USE_BIG_DECIMAL_FOR_FLOATS: true
  # aws与本地环境切换（aws: prod  本地：dev)
  profiles:
    active: dev

#beelt模板引擎配置
beetl:
  #模板路径
  templatesPath: templates
#mybatispluse
mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml,classpath*:/commonmapping/*.xml
  type-aliases-package: com.didu.lotteryshop
#email发送配置
logging:
  config:
    classpath: logback.xml