# 服务配置
server:
  port: 8080
#  servlet:
#    context-path: /
# Sping配置
spring:
  application:
    name: webGateway-service
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  #redis 缓存数据库配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.108.140.142:3306/lotteryshop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      filters: stat,wall,4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
#  # 模板引擎配置
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

#微服务注册服务配置
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
#beelt模板引擎配置
beetl:
  #模板路径
  templatesPath: templates
# zuul网关配置
zuul:
  routes:
    #eureka服务配置
    api-a:
      path: /eurekaserver/**
      serviceId:  eureka-service
      sensitiveHeaders: "*"
    #验证服务配置
    api-b:
      path: /authservice/**
      serviceId: auth-service
      sensitiveHeaders: "*"
    #api需要授权网关服务配置
    api-c:
      path: /api/**
      serviceId: apiGateway-service
      sensitiveHeaders: "*"
    #api不需要授权网关服务
    api-d:
      path: /apiauthorization/**
      serviceId: apiGateway-service
      sensitiveHeaders: "*"
    api-e:
      path: /manage/**
      serviceId: manage-service
      sensitiveHeaders: "*"
  #sensitiveHeaders: "*"
  #sensitive-headers: "*"
  #add-host-header: false
  ignored-headers:  '*'
  add-host-header: true

#security&oauth2 配置
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8083/auth/api/member # 资源服务认证
#    client:
#      client-id: browser # 认证服务ID
#      client-secret: browser # 认证服务密码
#      access-token-uri: http://localhost:8083/auth/oauth/token # 获取token
#      user-authorization-uri: http://localhost:8083/auth/oauth/authorize # 获取授权码
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:${server.port}/authservice/auth/api/member # 资源服务认证
#    client:
#      client-id: browser # 认证服务ID
#      client-secret: browser # 认证服务密码
#      access-token-uri: http://localhost:${server.port}/authservice/auth/oauth/token # 获取token
#      user-authorization-uri: http://localhost:${server.port}/authservice/auth/oauth/authorize # 获取授权码

# 提高延时设置 elevate timeout settings, 避免因为延时造成失败
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
# 负载均衡工具配置
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 7000
  MaxConnectionsPerHost: 50
  MaxTotalConnections: 200
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
#  eureka:
  #  enabled: false

zuul.host.maxTotalConnections: 200
zuul.host.maxPerRouteConnections: 10
logging:
  config: classpath:logback-boot.xml