# 服务配置
server:
  port: 8070
  serverlet:
    session:
      timeout:3600
# Sping配置
spring:
  application:
    name: manage-service
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
#security 配置
  security:
    user:
      name: didu123456didu
      password: 123456
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.17.0.1:3306/lotteryshop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: lottery
      password: Lottery2020@)@)
      filters: stat,wall,4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
#微服务注册服务配置
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka/
#beelt模板引擎配置
beetl:
  #模板路径
  templatesPath: templates
#mybatispluse
mybatis-plus:
  mapper-locations: classpath*:commonmapping/*.xml
  type-aliases-package: com.didu.lotteryshop.common.entity


