# 服务配置
server:
  port: 8070
  serverlet:
    session:
      timeout:3600
# Sping配置
spring:
  application:
    name: manage-service
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  # aws与本地环境切换（aws: prod  本地：dev)
  profiles:
    active: dev
#security 配置
  security:
    user:
      name: admin
      password: Lottery2020@)@)
#微服务注册服务配置
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka/
#beelt模板引擎配置
beetl:
  #模板路径
  templatesPath: templates
#mybatispluse
mybatis-plus:
  mapper-locations: classpath*:/mapping/*.xml,classpath*:/commonmapping/*.xml
  type-aliases-package: com.didu.lotteryshop.common.entity


