#微服务注册服务配置
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
#      defaultZone: http://172.17.0.1:8090/eureka/
      defaultZone: http://localhost:8090/eureka/