#微服务注册服务配置
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.17.0.1
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:8090/eureka/
      #defaultZone: http://localhost:8090/eureka/

#security&oauth2 配置
security:
  oauth2:
    resource:
      id: lotteryb-service
      user-info-uri: http://172.17.0.1:8083/auth/api/member # 资源服务认证
      prefer-token-info: false
    client:
      client-id: browser # 认证服务ID
      client-secret: browser # 认证服务密码
      grantType: password
      access-token-uri: http://172.17.0.1:8083/auth/oauth/token # 获取token
      user-authorization-uri: http://172.17.0.1:8083/auth/oauth/authorize # 获取授权码