#  Server configuration
server:
  port: 8090
  #servlet:
   # context-path: /eurekaServer

# Spring custom configuration
spring:
    application:
      name: eureka-service
    # aws与本地环境切换（aws: prod  本地：dev)
    profiles:
      active: dev